name: Action Sample

on:
  issues:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  check-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - run: pip install -r requirements.txt
      - run: echo ${{ github.event.issue.html_url }} >> input
      - run: python GitHub.py < input > output
      - run: cat output >> $GITHUB_ENV
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ${{ env.RESULT_OUTPUT }}
            })
